apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APPLICATION_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{APPLICATION_NAME}}
  template:
    metadata:
      labels:
        app: {{APPLICATION_NAME}}
    spec:
      containers:
        - name: {{APPLICATION_NAME}}
          image: {{IMAGE_NAME}}:latest
          ports:
            - containerPort: 3306
          env:
            - name: DB_NAME
              value: "{{DB_NAME}}"
            - name: DB_USER
              value: "{{USERNAME}}"
            - name: DB_PASSWORD
              value: "{{PASSWORD}}"
            - name: POSTGRES_PASSWORD  # Only used if PostgreSQL
              value: "{{POSTGRES_PASSWORD}}"
            - name: MYSQL_ROOT_PASSWORD  # Only used if MySQL/MariaDB
              value: "{{ROOT_PASSWORD}}"

            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_ENABLE_KRAFT
              value: "no"

            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: {{APPLICATION_NAME}}
spec:
  type: NodePort
  selector:
    app: {{APPLICATION_NAME}}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: {{NODE_PORT}}
